# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-index

includes:

  qdrant:
    taskfile: ./Taskfile.qdrant.yml

tasks:
  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}

  server:
    dotenv: ['.env' ]
    
    cmds:
      - go run main.go